# -*- mode: ruby -*-
# vi: set ft=ruby :

# Topology
#                   nw1                                                       nw2
#              10.0.101.0/24                                             10.0.103.0/24
#  server01 ------------------- switch01 ------------------- switch01 ------------------- server02
#       swp1 .2             .1 swp2  swp1                   swp1  swp2 .1             .2 swp2
#                           lo: 10.0.102.1/32           lo: 10.0.102.2/32
#

serverSettings = [
  {
    "box" => "ubuntu/jammy64",
    "box_version" => "20221004.0.0",
    "hostname" => "server01",
    "network" => {
      "name" => "nw1",
      "ip" => "10.0.101.2/24",
      "gateway" => "10.0.101.1"
    }
  },
  {
    "box" => "ubuntu/jammy64",
    "box_version" => "20221004.0.0",
    "hostname" => "server02",
    "network" => {
      "name" => "nw3",
      "ip" => "10.0.103.2/24",
      "gateway" => "10.0.103.1"
    }
  }
]

switchSettings = [
  {
    "box" => "CumulusCommunity/cumulus-vx",
    "box_version" => "4.3.1", # Could not boot 4.5.0 and 4.4.4 because of "Kernel panic - not syncing" error.
                              # Could not boot 4.4.0 because of "VBoxManage.exe: error: Appliance read failed" error.
    "hostname" => "switch01",
    "network" => [
      {
        "interface" => "lo",
        "ip" => "10.0.102.1/32"
      },
      {
        "name" => "nw2",
        "interface" => "swp1"
      },
      {
        "name" => "nw1",
        "interface" => "swp2",
        "ip" => "10.0.101.1/24"
      },
    ],
  },
  {
    "box" => "CumulusCommunity/cumulus-vx",
    "box_version" => "4.3.1", # Could not boot 4.5.0 and 4.4.4 because of "Kernel panic - not syncing" error.
                              # Could not boot 4.4.0 because of "VBoxManage.exe: error: Appliance read failed" error.
    "hostname" => "switch02",
    "network" => [
      {
        "interface" => "lo",
        "ip" => "10.0.102.2/32"
      },
      {
        "name" => "nw2",
        "interface" => "swp1"
      },
      {
        "name" => "nw3",
        "interface" => "swp2",
        "ip" => "10.0.103.1/24"
      },
    ],
  }
]

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048 # Allocated only 1024 mb made operation too slow.
    vb.cpus = 2      # Allocating only 1 cpu cause "Kernel panic - not syncing" error when booting vm.
  end

  switchSettings.each do |switchSetting|
    config.vm.define switchSetting["hostname"] do |device|
      # Every Vagrant development environment requires a box. You can search for
      # boxes at https://vagrantcloud.com/search.
      device.vm.box = switchSetting["box"]
      device.vm.box_version = switchSetting["box_version"]
      device.vm.hostname = switchSetting["hostname"]

      # Disable automatic box update checking. If you disable this, then
      # boxes will only be checked for updates when the user runs
      # `vagrant box outdated`. This is not recommended.
      # config.vm.box_check_update = false
      device.vm.box_check_update = false

      switchSetting["network"].each do |networkSetting|
        if networkSetting["name"] == nil
          next
        end
        # Create a private network, which allows host-only access to the machine
        # using a specific IP.
        # config.vm.network "private_network", ip: "192.168.33.10"
        device.vm.network "private_network", virtualbox__intnet: networkSetting["name"], auto_config: false
      end

      device.vm.provision "file",
        source: "conf/#{switchSetting["hostname"]}/etc/frr/daemons",
        destination: "/tmp/daemons"

      device.vm.provision "file",
        source: "conf/#{switchSetting["hostname"]}/etc/frr/frr.conf",
        destination: "/tmp/frr.conf"

      # Enable provisioning with a shell script. Additional provisioners such as
      # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
      # documentation for more information about their specific syntax and use.
      # config.vm.provision "shell", inline: <<-SHELL
      #   apt-get update
      #   apt-get install -y apache2
      # SHELL
      device.vm.provision "shell", inline: <<-SHELL
        sudo cp /tmp/daemons /etc/frr/daemons
        sudo cp /tmp/frr.conf /etc/frr/frr.conf
        sudo systemctl restart frr.service
      SHELL

      device.vm.provision "shell" do |shell|
        cmd = ""
        switchSetting["network"].each do |networkSetting|
          if networkSetting["ip"] == nil || networkSetting["ip"] == ""
            next
          end
          if networkSetting["interface"] == "lo"
            cmd += "sudo net add loopback #{networkSetting["interface"]} ip address #{networkSetting["ip"]}\n"
          else
            cmd += "sudo net add interface #{networkSetting["interface"]} ip address #{networkSetting["ip"]}\n"
          end
        end
        cmd += "sudo net commit\n"
        shell.inline = cmd
      end

      device.vm.provision "shell" do |shell|
        cmd = ""
        switchSetting["network"].each do |networkSetting|
          if networkSetting["interface"] == nil || networkSetting["interface"] ==""
            next
          end
          cmd += "sudo ip link set up #{networkSetting["interface"]}\n"
        end
        shell.inline = cmd
      end
    end
  end

  serverSettings.each do |serverSetting|
    config.vm.define serverSetting["hostname"] do |device|
      # Every Vagrant development environment requires a box. You can search for
      # boxes at https://vagrantcloud.com/search.
      device.vm.box = serverSetting["box"]
      device.vm.box_version = serverSetting["box_version"]
      device.vm.hostname = serverSetting["hostname"]

      # Disable automatic box update checking. If you disable this, then
      # boxes will only be checked for updates when the user runs
      # `vagrant box outdated`. This is not recommended.
      # config.vm.box_check_update = false
      device.vm.box_check_update = false

      # Create a private network, which allows host-only access to the machine
      # using a specific IP.
      # config.vm.network "private_network", ip: "192.168.33.10"
      device.vm.network "private_network", virtualbox__intnet: serverSetting["network"]["name"], auto_config: false 

      # Enable provisioning with a shell script. Additional provisioners such as
      # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
      # documentation for more information about their specific syntax and use.
      # config.vm.provision "shell", inline: <<-SHELL
      #   apt-get update
      #   apt-get install -y apache2
      # SHELL
      device.vm.provision "shell" do |shell|
        cmd = ""
        cmd += "sudo tee /etc/netplan/51-cloud-init.yaml << EOF\n"
        cmd += "network:\n"
        cmd += "  ethernets:\n"
        cmd += "    enp0s8:\n"
        cmd += "      dhcp4: false\n"
        cmd += "      dhcp6: false\n"
        cmd += "      addresses: [#{serverSetting["network"]["ip"]}]\n"
        cmd += "      routes:\n"
        cmd += "        - to: default\n"
        cmd += "          via: #{serverSetting["network"]["gateway"]}\n"
        cmd += "  version: 2\n"
        cmd += "EOF\n"

        cmd += "sudo netplan apply\n"

        shell.inline = cmd
      end
    end
  end
end
